// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckExistence(ctx context.Context, reference string) (bool, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentByIDWithLock(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentByReference(ctx context.Context, reference string) (Payment, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
}

var _ Querier = (*Queries)(nil)
